version: '3'


services:

  
  nats-server:
    image: nats:latest
    

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/tienda-microservices-428403/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/tienda-microservices-428403/image-registry/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  
  # Orders MS
  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: europe-southwest1-docker.pkg.dev/tienda-microservices-428403/image-registry/orders-ms
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222


  # ============================
  # Payments Microservice
  # ============================
  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/tienda-microservices-428403/image-registry/payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=${PAYMENTS_MS_PORT}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}


  # ============================
  # Auth Microservice
  # ============================
  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/tienda-microservices-428403/image-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}